# 1.Write a Python function to list even and odd numbers in a list


In [14]:
lst=[1,2,3,4,5,6,7,8,9,10]
odd=[]
even=[]
def divide():
    for i in lst:
        if i%2==0:
            even.append(i)
        else:
            odd.append(i)
        
divide()       
print('Even numbers in given list are:',even)
print('Odd numbers in given list are:',odd)

Even numbers in given list are: [2, 4, 6, 8, 10]
Odd numbers in given list are: [1, 3, 5, 7, 9]


# 2. Write and run a program that asks the user to enter 8 integers(one at a time), and then prints how many of those integers were even numbers. For example if the user entered 19,6,9,20,13,7,6, and 1,then your program should print out 3 since 3 of those numbers were even.

In [7]:
lst=[]
for i in range(8):
    lst.append(int(input("enter the number:")))
    
def even():
    count=0
    for x in lst:
        if x%2==0:
            count+=1
    return count
even()

enter the number:19
enter the number:6
enter the number:9
enter the number:20
enter the number:13
enter the number:7
enter the number:6
enter the number:1


3

# 3. Write a Python program where you take any positive integer n,if n is even,divide it by 2 to get n/2. If n is odd,multiply it by 3 and add 1 to obtain 3n+1. Repeat the process until you reach 1.

In [2]:
n=int(input("enter the number:"))

def get(n):
    while n!=1:
        if n%2==0:
            n=n/2
        else:
            n=3*n+1
    return n
get(n)

enter the number:20


1.0

# 4. Write a python program to compute the sum of all the multiples of 3 or 5 below 500

In [5]:
def sumfun():
    sum=0
    for i in range(1,500):
        if i%3==0 or i%5==0:
            sum+=i
    return sum

sumfun()
        







57918

# 5.To write a python program to find first 'n' prime numbers from a list of given numbers. 

In [7]:
def prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

def fun(n, lst):
    primelst = []
    for num in lst:
        if prime(num):
            primelst.append(num)
            if len(primelst) == n:
                break
    return primelst

n = 6
lst = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

primelst = fun(n,lst)
print(f"The first {n} prime numbers from the given list are: {primelst}")

The first 6 prime numbers from the given list are: [2, 3, 5, 7, 11, 13]


# 6.To write a python program to compute matrix multiplication

In [1]:
import numpy as np

A = [[12, 7, 3],[4, 5, 6],[7, 8, 9]]
B = [[5, 8, 1, 2],[6, 7, 3, 0],[4, 5, 9, 1]]
 
result = np.dot(A,B)
print(result)


 


[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]


# 7.Write a python function to count the number of vowels in a string

In [38]:

def vow(s):
    count=0
    vow=['a','e','i','o','u']
    for i in s:
        if i in vow:
            count+=1
    return count

s=input()
vow(s)
    
        

aeroplane


5

# 8.Write a python function for finding factorial of the given number using a recursive function

In [10]:
def fact(n):
    if n==0 or n==1:
        return 1
    else:
        return n*fact(n-1)

n=int(input("enter the number:"))
fact(n)

enter the number:3


6

# 9.Write a Python function for generating the fibonacci series using the function

In [13]:
def fib(n):
    a, b = 0, 1
    for i in range(n):
        a, b = b, a + b
    return a

        
n=int(input("enter the number:"))
fib(n) 
        

enter the number:6


8

# 10.Python program to display the given integer in reverse order using the function without an in-built function

In [22]:
def rev(n):
    rev_num=0
    while n > 0:
        rev_num = rev_num * 10 + n % 10
        n //= 10
    return rev_num
n=int(input("enter the number:"))
rev(n)
        

enter the number:268


862

## 11.Write a python function to display all integers within the range 200-300 whose sum of digits is an even number

In [26]:
def evensum():
    for n in range(200,300):
        sum=0
        for i in str(n):
               sum+=int(i)
        if sum%2==0:
            print(n)
            
evensum()

200
202
204
206
208
211
213
215
217
219
220
222
224
226
228
231
233
235
237
239
240
242
244
246
248
251
253
255
257
259
260
262
264
266
268
271
273
275
277
279
280
282
284
286
288
291
293
295
297
299


# 12.Write a python function to find the number of digits and sum of digits for a given integer

In [33]:
def dig(n):
    num = 0
    sum = 0
    while n > 0:
        num += 1
        sum+= n % 10
        n //= 10
    return num, sum


n=int(input("enter the number:"))
num,sum=dig(n)
print('the number of digits are:',num)
print('the sum of digits is:',sum)


        

enter the number:294
the number of digits are: 3
the sum of digits is: 15


###### 

# 13.Write functions called is_sorted that takes a list as a parameter and returns True if the list is sorted in ascending order and False otherwise and has_duplicates that takes a list and returns True if there is any element that appears more than once. It should not modify the original list

In [5]:
def is_sort(lst):
    return lst==sorted(lst)
def dup(lst):
    return len(lst)!=len(set(lst))
lst=[1,2,3,4,5,5,6,7,8]
print("Is the given list sorted?",is_sort(lst))
print("Are there any duplicate values?",dup(lst))

Is the given list sorted? True
Are there any duplicate values? True


# 14. Write functions called nested_sum that takes a list of integers and adds up the elements from all the nested lists and cumsum that takes a list of numbers and returns the cumulative sum,that is,a new list where the i(th) element is the sum of the first i+1 elements from the original list.

In [13]:
def nested_sum(lst):
    total = 0
    for element in lst:
        if isinstance(element, list):
            total += nested_sum(element)
        else:
            total += element
    return total

def cumsum(lst):
    cumulative_sum = 0
    result = []
    for num in lst:
        cumulative_sum += num
        result.append(cumulative_sum)
    return result

nested_list = [1, 2, [3, 4, [5, 6]], 7, [8, 9]]
result_nested_sum = nested_sum(nested_list)
print(result_nested_sum) 


original_list = [1, 2, 3, 4, 5]
result_cumsum = cumsum(original_list)
print(result_cumsum)

45
[1, 3, 6, 10, 15]
