# 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[0.16980938 0.44104102 0.55644979]
  [0.60459831 0.45168907 0.80548855]
  [0.33267145 0.87102259 0.49425827]]

 [[0.41568729 0.7346272  0.34763027]
  [0.61603338 0.25235916 0.55089728]
  [0.55569228 0.46845746 0.55314458]]

 [[0.11625735 0.93391752 0.00574158]
  [0.32663679 0.35251584 0.54094124]
  [0.20298218 0.08734152 0.81025308]]]


# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
import numpy as np

# Create a 5x5 matrix with values 1, 2, 3, 4 below the diagonal
matrix = np.diag(1 + np.arange(4), k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3. Create a 8x8 matrix and fill it with a checkboard pattern

In [4]:
import numpy as np

# Create an 8x8 matrix filled with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5X5 random matrix

In [5]:
import numpy as np

# Create a random 5x5 matrix
random_matrix = np.random.rand(5, 5)

# Calculate the mean and standard deviation of the matrix
mean = np.mean(random_matrix)
std_dev = np.std(random_matrix)

# Normalize the matrix
normalized_matrix = (random_matrix - mean) / std_dev

# Print the normalized matrix
print("Original matrix:")
print(random_matrix)
print("\nNormalized matrix:")
print(normalized_matrix)

Original matrix:
[[0.82907405 0.24329697 0.40414258 0.77947832 0.47844081]
 [0.46236158 0.26391576 0.61926824 0.3823945  0.28891669]
 [0.35479738 0.93271637 0.87630725 0.19425235 0.58127638]
 [0.1812663  0.0761455  0.06961581 0.38454124 0.65873481]
 [0.66370918 0.6602797  0.64327487 0.7577667  0.08911544]]

Normalized matrix:
[[ 1.38266465 -0.90482686 -0.27671598  1.18899062  0.01342267]
 [-0.04936759 -0.82430935  0.56336149 -0.36164341 -0.72667936]
 [-0.46941166  1.78739356  1.56711289 -1.09634878  0.41500121]
 [-1.14706    -1.5575625  -1.58306127 -0.35326026  0.71748061]
 [ 0.73690577  0.72351348  0.6571087   1.10420553 -1.50691415]]


# 5. How to find common values between two arrays?

In [6]:
import numpy as np

# Define two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find the common values between the two arrays
common_values = np.intersect1d(array1, array2)

print("Common Values:", common_values)

Common Values: [3 4 5]


# 6. How to get the dates of yesterday,today and tomorrow?

In [7]:
from datetime import datetime, timedelta

# Get the current date (today)
today = datetime.now()

# Calculate yesterday and tomorrow dates
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

# Format the dates as strings (optional)
today_str = today.strftime('%Y-%m-%d')
yesterday_str = yesterday.strftime('%Y-%m-%d')
tomorrow_str = tomorrow.strftime('%Y-%m-%d')

print("Yesterday:", yesterday_str)
print("Today:", today_str)
print("Tomorrow:", tomorrow_str)

Yesterday: 2023-09-21
Today: 2023-09-22
Tomorrow: 2023-09-23


# 7. Consider two random array A and B, Check if they are equal

In [8]:
import numpy as np

# Create two random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are not equal.


# 8. Create random vector of size 10 and replace the maximum value by 0

In [9]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random Vector with the Maximum Value Replaced:")
print(random_vector)

Random Vector with the Maximum Value Replaced:
[0.48333904 0.63128584 0.         0.89938572 0.82292549 0.34336777
 0.49938806 0.06871886 0.73390847 0.84307001]


# 9. How to print all the values of an array?

In [10]:
import numpy as np

# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Print all the values of the array
for value in my_array:
    print(value)

1
2
3
4
5


# 10. Subtract the mean of each row of a matrix

In [11]:
import numpy as np

# Create a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the row-wise means
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row-wise means from the matrix
normalized_matrix = matrix - row_means

print("Original Matrix:")
print(matrix)

print("\nMatrix with Row-Means Subtracted:")
print(normalized_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row-Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11. Consider a given vector, how to add 1 to each element indexed by a second vector( be careful with repeated indices)?

In [12]:
import numpy as np

# Given vector
given_vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Second vector containing indices where you want to add 1
indices_to_add_1 = np.array([1, 3, 5, 1, 7])

# Find unique indices to avoid repeated additions
unique_indices = np.unique(indices_to_add_1)

# Add 1 to elements at unique indices
given_vector[unique_indices] += 1

print("Modified Vector:")
print(given_vector)

Modified Vector:
[1 3 3 5 5 7 7 9 9]


# 12. How to get the diagonal of a dot product?

In [13]:
import numpy as np

# Define two matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Compute the dot product of A and B
dot_product = np.dot(A, B)

# Extract the diagonal elements of the dot product matrix
diagonal_elements = np.diag(dot_product)

print("Dot Product Matrix:")
print(dot_product)

print("\nDiagonal Elements of Dot Product:")
print(diagonal_elements)

Dot Product Matrix:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal Elements of Dot Product:
[30 69 90]


# 13. How to find the most frequent value in an array?

In [21]:
x = np.random.randint(0,10,50)
x

array([9, 8, 7, 9, 3, 6, 6, 3, 7, 8, 7, 3, 0, 1, 2, 9, 7, 1, 8, 7, 9, 8,
       3, 6, 2, 6, 9, 6, 9, 9, 3, 9, 7, 8, 5, 2, 8, 0, 8, 3, 5, 8, 9, 9,
       1, 0, 6, 6, 8, 7])

In [22]:
import numpy as np

# Create the random NumPy array
x = np.random.randint(0, 10, 50)

# Use NumPy to find the most frequent value
most_common_value = np.bincount(x).argmax()

print("Most frequent value:", most_common_value)

Most frequent value: 0


# 14. How to get the n largest values of an array

In [16]:
import numpy as np

# Create an example NumPy array
arr = np.array([3, 1, 9, 4, 7, 2, 10, 5, 6])

# Specify the value of n for the n largest values
n = 3

# Use numpy.partition to get the n largest values
n_largest = np.partition(arr, -n)[-n:]

print(f"The {n} largest values in the array are: {n_largest}")

The 3 largest values in the array are: [ 7  9 10]


# 15. How to create a record array from a regular array?

In [23]:
import numpy as np

# Create a regular NumPy array
regular_array = np.array([[1, 'vani', 25],
                          [2, 'tejaswi', 18],
                          [3, 'teju', 22]])

# Define field names for each column
dtype = [('ID', int), ('Name', 'U10'), ('Age', int)]

# Create a record array using numpy.rec.fromarrays
record_array = np.rec.fromarrays(regular_array.T, dtype=dtype)

# Access elements by field name
print("Record Array:")
print(record_array)

# Access elements by field name
print("\nAccessing by Field Name:")
print("ID:", record_array['ID'])
print("Name:", record_array['Name'])
print("Age:", record_array['Age'])

Record Array:
[(1, 'vani', 25) (2, 'tejaswi', 18) (3, 'teju', 22)]

Accessing by Field Name:
ID: [1 2 3]
Name: ['vani' 'tejaswi' 'teju']
Age: [25 18 22]


# 16.  How to swap two rows of an array?

In [18]:
import numpy as np

# Create an example 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Define the indices of the rows you want to swap
row1_index = 0  # Index of the first row (0-based)
row2_index = 2  # Index of the second row (0-based)

# Swap the rows
array[row1_index], array[row2_index] = array[row2_index].copy(), array[row1_index].copy()

print("Array with Rows Swapped:")
print(array)

Array with Rows Swapped:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17. Write python code to reshape to the next dimension of numpy array?

In [19]:
x=np.array([[23,34, 121],[23,22,67],[686,434,123]])
x

array([[ 23,  34, 121],
       [ 23,  22,  67],
       [686, 434, 123]])

In [20]:
import numpy as np

# Create the original array
x = np.array([[23, 34, 121],
              [23, 22, 67],
              [686, 434, 123]])

# Reshape the array to the next dimension
reshaped_array = x.reshape(-1, x.shape[-1])

print("Original Array:")
print(x)

print("\nReshaped Array to the Next Dimension:")
print(reshaped_array)

Original Array:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]

Reshaped Array to the Next Dimension:
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]
